version: '3'

services:

    holidays:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: holidays
        ports:
            - "3308:3306"
            
    users:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: users
        ports:
            - "3309:3306"
            
    admin:
        image: adminer
        ports:
            - 8080:8080